[tox]
isolated_build = True
envlist =
    py36
    py37
    py38
    py39
    py310
    py311
    py312
    py313
    py314
    lint

[testenv]
skip_missing_interpreters = True
extras =
    test
commands =
    pytest --cov --cov-report=term-missing {posargs}

[testenv:lint]
skip_install = true
deps =
    pre-commit
commands =
    pre-commit run --all-files

[testenv:docs]
extras =
    doc
commands =
    sphinx-build -b html docs dist/docs
